### PR TITLE
fix: dump the grid for the horizontal flow view, add links/tooltips to connections

### LINKED ISSUE #242: integration details - flow view doesn't work for large integrations
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I think because it's trying to use the grid system to lay out the icons but this won't work with non-trivial integrations:

image

### PR DESCRIPTION
**Pull request by gashcrumb**
fixes #242

image

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1168/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
I moved around some of the logic and reorganized some functions.  The editor shows the right icons and step names now as well as data shapes at least like the angular app.  Tough bit was that toUIStepKindCollection() is used from a couple different sources but I think this kinda works, most mapping should occur now in `toUIStepKind`.  I haven't tackled getting the URL out of there, trouble is in a couple cases a connection has a `data:` or `extension:` URI scheme, which means constructing a URL for the backend vs a URL for a static asset.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1180/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
With the latest push the correct steps are shown based on where you are in the flow:

image

I did unfortunately break the link for selecting a step from this page, it's kinda complicated mapping between the api and UI models here and there, but coming along.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1186/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
Links work again.  There's a few spots that are a bit bruised still, but the behavior is looking correct.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1188/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Pull request merged**
