### PR TITLE
fix: Swap out TODOs with generic api error element

### LINKED ISSUE #168: Create "can't talk to the server" error page
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
We're accumulating TODO pages such as:

image

When the UI is unable to talk to the backend on a given view.

We could use a generic error page/element for this.  Probably an element.

@dongniwang @seanforyou23 is there a patternfly example you could link here maybe?

### PR DESCRIPTION
**Pull request by gashcrumb**
fixes #168

Also added in a quick storybook for `UnrecoverableError` just so it's there.

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/753/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
Rebased and found the rest of 'em

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/765/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
This needs a re-approve looks like, turns out I missed some imports on the first pass.

**Pull request merged**
