### PR TITLE
feat: add array and custom component support to auto-form

### LINKED ISSUE #251: Editor - Implement the basic filter step configuration page.
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The basic filter configuration page is a custom page for the built in `ruleFilter` step kind.  This issue tracks implementing this page, which consists of a slightly more advanced form featuring an array of input values.  Each array element has a string input that [fetches typeahead data](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.component.ts#L164-L173) from the server as the user types a select element the user uses to choose a match operator, and finally an open text element where the user types their filter criteria.  The user can add and remove lines at will.

image

Upon clicking save the UI [organizes](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.component.ts#L224-L228) the resulting form data ([example](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.component.ts#L56-L72)) into the `configuredProperties` attribute.

The angular app used ng-dynamic-forms directly to implement the UI, so not much point in linking to any of that code.  Autoform *could* be extended to support this UI but it might be faster and more reasonable to just implement it using a hand-coded form.  The backend appears to use tokens for comparison operators instead of words, so the angular UI [mapped them](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-configure/filter-steps/filter.interface.ts#L20-L61).

### LINKED ISSUE #322: auto-forms - custom component support
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
It'd be awesome if we could expand on the available types auto-form supports by adding the ability to map custom types to custom components.  This would allow folks to write more advanced form fields that perform more custom validation logic etc.

### PR DESCRIPTION
**Pull request by gashcrumb**
fixes #251 
fixes #322
relates to #334

Realized with my initial effort I wasn't using Formik properly, so I've added some initial array support to auto-form in addition to custom component support.  The basic filter step still looks the same as previous screenshots I've sent out, but now the trash icons and the "Add another rule" link do stuff.

image

The connector/connection details validation was a bit of a pita for the refactoring effort needed.  I created #334 to track this and will fix it in a subsequent PR.

Originally I was going to use the pf4 typeahead select-y thingie along with custom component support in auto-form, but turns out it looks terrible out of the box amidst everything and the buttons trigger form submit events.  So I went with the same solution as the angular app with a data list.

So now with this PR auto-form supports arrays, a `dataList` property config of an array of strings to act as completions, custom component support.

Loading and saving should be working.  The "done" button is enabled when it shouldn't be, I'll raise an issue for that to do in a subsequent PR, the validation needs to be further enhanced to support arrays and Formik's array notation.

### CODE REVIEW

**Comment by gashcrumb** [comment]
You can try and add one to "DescribeDataAbuse" or look at the one in "From React" to play with it.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1694/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1702/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1747/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1753/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1755/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Pull request merged**
