### PR TITLE
feeat: merge connections, extensions and steps 

### PR DESCRIPTION
**Pull request by riccardo-forina**
Merge connections, extensions, and steps when showing a list of possible connections when adding a step to an integration.

steps

I think we are missing some asset in our codebase.

### TODO

* [ ] filter steps based on the current position.
* [ ] hook all the kinds to an href returner.

### CODE REVIEW

**Comment by gashcrumb** [comment]
That is a very promising gif :smile_cat:

**Comment by riccardo-forina** [comment]
Damn it looks like something changed on the BE side, and it breaks the apis. I had them already compiled and didn’t got the error on my end :(

**Comment by gashcrumb** [comment]
we'll need to rebase our fork I think.

**Comment by riccardo-forina** [comment]
So the missing model has been moved to the internal swagger.json, so I added that to the `models` package too. Since I was there, I also resynced all with upstream and we have the new assets.

**Comment by gashcrumb** [comment]
Works for me, great!

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/879/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
Maybe better merge this and I’ll address the todo later?

**Pull request merged**
