### PR TITLE
fix: expose the isInitialValid property and set it appropriately in the editor, add some IDs

### LINKED ISSUE #270: auto-form should indicate a form is valid when supplied a valid defaultValue property value
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Currently when auto-form is given a value that is valid, the form doesn't set the isValid render property to true, so this can happen:

image

Seems to be if the form isn't dirty in this case it isn't valid, as if you change the select property on the above, the 'Next' button is enabled, however changing it back to the "add_lead" setting disables the next button again :confused: 

This code [works around this](https://github.com/syndesisio/syndesis-react/blob/master/app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx#L137-L140) by validating the form value first, and then [setting this flag](https://github.com/syndesisio/syndesis-react/blob/master/app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx#L158) but I don't think it should be necessary.

### LINKED ISSUE #286: Next button is active only after Period interaction in Simple Timer action
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Currently when I have Timer as start connection and I select 'Simple Timer' I have to interact with 'Period' otherwise 'Next' is inactive. I have to do this even if I want to keep the default value. 
screenshot_20190515_113243

### PR DESCRIPTION
**Pull request by gashcrumb**
fixes #270
fixes #286

and some stuff for #304

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1551/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
create integration is broken, need to sort that

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1560/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1570/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
K,  should be all set.

**Comment by riccardo-forina** [comment]
Now it doesn’t crash anymore - thanks! - but the next button is still disabled

**Comment by gashcrumb** [comment]
Found it!  Loads of reasons for this button to be disabled initially apparently :smile: 

It just occurred to me that the form doesn't seem to be indicating required fields which would obviously help here, lemme figure that out too.

**Comment by gashcrumb** [comment]
Added the required field indicator.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1583/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Pull request merged**
