### PR TITLE
chore: overall layout cleanup

### PR DESCRIPTION
**Pull request by riccardo-forina**
Also move the integration titles in the wizard body.

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1151/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
Looking good!  Those editor pages are a tough call, with the name and description there and then if we go and add a toolbar row in addition it's like 1/3 of the vertical space is occupied by a header.

**Comment by riccardo-forina** [comment]
Yeah I’m not a fan either

**Comment by riccardo-forina** [comment]
But it's also how a page with breadcrumb, a title, and a description is supposed to look like http://patternfly-react.surge.sh/patternfly-4/demos/pagelayout/pagelayouthorizontalnav/ so I guess it's ok?

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1162/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
editor-layout

Preview of the latest changes.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1164/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1166/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Pull request merged**
