### PR TITLE
Connections UI Work

### PR DESCRIPTION
**Pull request by elvisisking**
- implemented ConnectionDetailsPage
- added kebab menu to connection card in list view
- see commit messages for additional details

**Outstanding Issues**
- on details page, if no description, and in readonly mode, there should be placeholder text
- on details page if you change/save the description, then change/save the name, then go back to list, the new description is lost. If changing only the name, or only the description, then go back to the list it works fine.
- the "Edit" menu item of the card kebab needs to be implemented yet
- on details page if you make changes in the form then cancel editing, the original values are not reset in the form
- on the details page, backend validation of the name happens on each keystroke. I added code that is not working because the `setState` call I added is async and does not happen when I had thought.

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/824/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
Hmm, there's this:

image

**Comment by gashcrumb** [comment]
Nice work though, the UI works nicely!  For some reason against staging I can't click on the salesforce connection, but that probably was configured via oauth and may not have any config.

**Comment by riccardo-forina** [comment]
* [x] on details page, if no description, and in readonly mode, there should be placeholder text
* [x]  on details page if you change/save the description, then change/save the name, then go back to list, the new description is lost. If changing only the name, or only the description, then go back to the list it works fine.
* [x] the "Edit" menu item of the card kebab needs to be implemented yet
on details page if you make changes in the form then cancel editing, the original values are not reset in the form
* [x] on the details page, backend validation of the name happens on each keystroke. I added code that is not working because the setState call I added is async and does not happen when I had thought.

This should be good to go now.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/841/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
oh and here I merged that other PR that fixed the connection icon helper, this just needs a rebase.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/861/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Pull request merged**
