### PR TITLE
feat: add multi-select support to autoform, also add a convertor function for form definitions from the API

### LINKED ISSUE #174: Implement support for multi-select control in auto-form
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Multi-select support was added to the old codebase, and we'll need the same for auto-form

### LINKED ISSUE #191: autoform: Support labelTooltip, controlTooltip and description properties
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
These properties aren't currently applied to the created form at all.

### PR DESCRIPTION
**Pull request by gashcrumb**
fixes #174
fixes #191 

Rebased, ready for review.  For whatever reason, building changed the internal model .d.ts file, so I committed that too and I had to add a workaround because of that annoying OptionalInt type that keeps leaking out of the java code into the swagger file.

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/874/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
Forms look finished now too :grin: 

image

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/884/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/889/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Pull request merged**
