### PR TITLE
chore: fix some broken links

### PR DESCRIPTION
**Pull request by riccardo-forina**
This should make the built UI - the one under GH pages - accessible again

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/532/artifacts/0/home/circleci/project/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/539/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
Storybook works but the app link leads me to a blank white page, looks like the static assets 404.

**Comment by gashcrumb** [comment]
I mean from the PR storybook link btw.

**Comment by riccardo-forina** [comment]
Thx, I missed one url in the config, force-pushing an update.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/541/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
yeeeh it works!

**Pull request merged**
