### PR TITLE
chore: DRY the editor

### PR DESCRIPTION
**Pull request by riccardo-forina**
Sorry @gashcrumb, I could have figured out this earlier 😅

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1302/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
Actually, let me check if I can pull off something similar for the actual apps.

**Comment by gashcrumb** [comment]
:+1: less code!

**Comment by riccardo-forina** [comment]
I think this is good enough for the moment.

**Comment by riccardo-forina** [comment]
https://github.com/syndesisio/syndesis-react/blob/768c1e75f8b97a75756c7e752c78e2eb3634cd7d/app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx

This is where new configurators (I really don't know how to call them, is configurator an ok name?) need to be wired. The idea is that since the whole editor app is built on top of the `subSteps` routes and relative resolvers, we can assume how all the "configurators" should be wired. The only exercise left to the consumer of the `EditorApp` is to tell the editor mode (if it's editing an existing step or adding a new one) and where to when canceling the configurator and when mutating the integration.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1313/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
On this amq 2 log integration if I go and look at the template step it's listed twice in the sidebar:

image

**Comment by gashcrumb** [comment]
Also 'Cancel' from say the action configuration page for a connection takes me back to the integration list, it used to take me to the add step page.

**Comment by gashcrumb** [comment]
Similar happens when I go to this sql2sql integration and click 'configure' for the finish step:

image

Also the 'Next' button is disabled even though there's valid config.  I added [this bit](https://github.com/syndesisio/syndesis-react/blob/master/app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx#L137-L140) to get around it.  Though I guess actually it'd be better to figure out why it's setting `isValid` to false even if the input data is valid, doesn't need to happen for this PR.

**Comment by riccardo-forina** [comment]
> Also the 'Next' button is disabled even though there's valid config. I added [this bit](https://github.com/syndesisio/syndesis-react/blob/master/app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx#L137-L140) to get around it. Though I guess actually it'd be better to figure out why it's setting `isValid` to false even if the input data is valid, doesn't need to happen for this PR.

Yeah, that happens when there is a default value. I haven't thought about how to fix it.

**Comment by riccardo-forina** [comment]
Btw sidebar and cancel buttons should be ok now.

**Comment by gashcrumb** [comment]
> Yeah, that happens when there is a default value. I haven't thought about how to fix it.

Lemme get an issue raised for it, we'll see this kinda thing in a few places.

> Btw sidebar and cancel buttons should be ok now.

Awesome!  Will retest and see if I spot anything else.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1316/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Pull request merged**
