### PR TITLE
chore(ux-edits): apply ux enhancements

### PR DESCRIPTION
**Pull request by seanforyou23**
This PR makes some adjustments to the fonts on the dashboard and also brings in the ClipboardCopy component for the copy uri function in the settings module.

Screen Shot 2019-05-20 at 5 55 05 PM

align font sizes across dashboard metrics
pf4 copy to clipboard for callback uri
give uptime metrics a test anchor

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1651/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1654/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
I don't know if it's this PR adding this but I didn't have my window maximized when I took a peek and it's like:

image

I dunno we should probably start either hiding columns or letting stuff wrap better.

**Comment by riccardo-forina** [comment]
It's a problem we had already. This is from latest staging 
Screenshot 2019-05-21 at 08 33 20

The issue is that the PF3 ListViewItem uses media query breakpoints to decide how to reflow its content, but it assumes that the list will take the full width of the page (with some allowance for the sidebar I guess). 

Without explicitly setting the `stacked` property, items will be forced on one line only until a "mobile" breakpoint is reached, but this way there is a range of widths - like the one in the screenshot - that will reflow very badly.

**Comment by seanforyou23** [comment]
Thx for the feedback, I'll look into the layout issues for dashboard today!

**Pull request merged**
