### PR TITLE
Fixes an issue when deleting an integration from it's detail page

### PR DESCRIPTION
**Pull request by elvisisking**
- see issue syndesisio/syndesis#5578
- added WithRouter to WithIntegrationActions
- after a successful delete, the integrations list page is displayed

### CODE REVIEW

**Comment by riccardo-forina** [comment]
What if I delete the integration from the dashboard? Will it go to the integrations list?

**Comment by elvisisking** [comment]
It does now go to the list page @riccardo-forina:( I need to fix that.

**Comment by riccardo-forina** [comment]
I dunno it’s not that big of a deal I think. @dongniwang what do you think? Is it a problem if users are redirected to the integrations list page after deleting an integration, regardless of where they were? Eg. deleting from the dashboard will take you to the integrations list page.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/2215/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
I think the redirect should only occur if you're on the detail page.  It'd definitely be weird to delete an integration on the dashboard there and then wind up on the integration list page.

**Comment by dongniwang** [comment]
Yeah, I think it makes sense to delete and return to the integration list when you're on the details page. 

But if delete happens from the dashboard, I would expect to see a confirmation dialog then a toast notification saying that the delete was successful. 

We (meaning UX) should be better in documenting these interactions. Thanks for fixing the behavior! And I think it's not a big deal that it takes users back to the list page.

**Comment by elvisisking** [comment]
@riccardo-forina @gashcrumb wdyt of this code that conditionally redirects to the integrations list page only when on the integration details page:
```
if (history.location.pathname.endsWith("details")) {
  history.push(resolvers.list());
}
``` 
And might there be a better way to do this?

**Comment by riccardo-forina** [comment]
Yeah, please no :D

What about adding a `postDeleteHref: H.LocationDescriptionObject` property to the `WithIntegrationActions` component, and let the consumers of that component specify the right URL to use for the redirect?

**Comment by elvisisking** [comment]
Yeah that is much nicer @riccardo-forina . Will do.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/2322/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by elvisisking** [comment]
While things are working as expected when an integration is deleted (redirect to list when on details page, otherwise stay on same page), I'm getting the following error in the console when the delete action from the kebab menu on the integration `DetailsPage` and `MetricsPage` is used:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Fetch (created by Context.Consumer)
    in SyndesisFetch (created by WithChangeListener)
    in WithChangeListener (created by Context.Consumer)
    in Fetch (created by Context.Consumer)
    in SyndesisFetch (created by WithIntegration)
    in WithIntegration (created by WithMonitoredIntegration)
    in WithMonitoredIntegration (at DetailsPage.tsx:46)
    in Route (created by WithRouteData)
    in WithRouteData (at DetailsPage.tsx:44)
    in Translation (at DetailsPage.tsx:40)
    in DetailsPage (created by Context.Consumer)
```
It seems like the code in [`ChangeListener.componentWillUnmount()`](https://github.com/syndesisio/syndesis/blob/master/app/ui-react/packages/api/src/WithChangeListener.tsx#L48) should not let this happen but not sure. I've tried a few things in the details page to fix this but seems like this could be a bigger issue especially when deleting objects from detail pages.

**Comment by gashcrumb** [comment]
Raise an issue for that and I'll investigate next week, shouldn't be a
problem for getting this pr merged I think.  Unless you want to look into
it further that is.

**Comment by riccardo-forina** [comment]
Ooooh it was the Fetch raising the warning, you didn’t t mention that! That’s the `fetch` promise that will still trigger even if the `Fetch` component has been unmounted. The problem is that no browser implements abortable fetches, so there is no way to work around this without replacing the browser’s own `fetch` with some polyfilled version that’s abortable, like `whatwg-fetch` (which is basically an `xhr` request wrapped in a `fetch` compatible interface). Or drop it in favor of something like `axios`.

Anyway, this isn’t something urgent, the warning is safe to ignore in this case (but should be ultimately addressed)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/2370/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/2380/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by paoloantinori** [comment]
@riccardo-forina with your last comment, are you saying that we can merge this?

**Pull request merged**
