### PR TITLE
[DO NOT MERGE] test commit that uses pf4 Alert component

### PR DESCRIPTION
**Pull request by riccardo-forina**
Just leveraging CI to see if this generally works.

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/603/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by seanforyou23** [comment]
Update: While this PR built for me just fine, it still seems the integration with PF4 is still pretty fragile. I don't understand why there needs to be two occurrences of `@patternfly/react-core` in the package.json. In addition, after installing `@patternfly/patternfly` I found myself looking at the same error as I was seeing previously (below)

Screen Shot 2019-04-17 at 10 16 54 AM

**Comment by seanforyou23** [comment]
Another update: @riccardo-forina found that by adding `"**/rxjs"` to the nohoist array in the root package.json, the problems go away.

**Comment by riccardo-forina** [comment]
This should not be needed anymore

**Pull request closed without merging**
