### PR TITLE
feat: add data mapper step configurator

### PR DESCRIPTION
**Pull request by riccardo-forina**
TODO: show the mapping warning icons on the IVP too. Also the "consider adding an aggregate step" icon needs to be implemented.

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1386/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1389/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1391/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1399/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1401/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1430/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1434/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1436/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1438/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1443/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1454/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1458/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1463/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
Ok I surrender, I can't get Atlasmap to work when deployed on CI. This will need to be checked out locally I'm afraid.

Atlasmap is embedded and wired up. Configuring an existing mapping or adding a new one through the link in the popup that opens clicking the warning icon should all work.

Those tooltips are custom, they don't close when clicking the body or when opening another one.

**Comment by igarashitm** [comment]
Hmm I tried opening data mapper step in the sql2sql integration but got white screen, console had this
```
Uncaught TypeError: Cannot read property 'id' of undefined
    at Object.children (IntegrationEditorApp.tsx:104)
    at utils.js:619
    at react-router.js:430
    at Aa (react-dom.production.min.js:4074)
    at qi (react-dom.production.min.js:5514)
    at Yi (react-dom.production.min.js:5536)
    at zc (react-dom.production.min.js:5958)
```
maybe I stepped on something under construction?

**Comment by riccardo-forina** [comment]
No, it looks like the servive worker that updates the cache of the staging website is being blocked by the oauth proxy, causing it to fail to update and thus, update the app.

@zregvart can we add `/service-worker.js` to the list of whitelisted files, please?

**Comment by riccardo-forina** [comment]
And actually I think there is a bug, but hopefully it will be fixed as soon as #292 lands

**Comment by riccardo-forina** [comment]
@igarashitm this should be fixed now. Can you try again with staging? You should get a notification about a new version of the app available, click the reload button in it first :)

**Comment by riccardo-forina** [comment]
...right, not really, we have a misconfiguration on staging, sorry about that 😭

**Comment by igarashitm** [comment]
Yep I got that notification, and after reload I went into "Edit" of sql2sql data mapper step, then I got network error `Failed to load resource: net::ERR_NAME_NOT_RESOLVED` and this url looks very fishy  `baseJSONInspectionServiceUrl: "https://syndesis-react-staging.b6ff.rh-idev.openshiftapps.comhttps://syndesis-react-staging.b6ff.rh-idev.openshiftapps.com/api/v1/atlas/json/"`

**Pull request merged**
