### PR TITLE
fix(support): left align expanded panel form

### PR DESCRIPTION
**Pull request by mcoker**
Left aligns the content in the expandable panel on support page.

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1630/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by dongniwang** [comment]
@mcoker looks good to me! thanks! 

Two questions:
- Do we have pagination for the "Specific Integrations" table? 
- For the table, do we have "# of # items" e.g. 6 of 20 items 

cc: @seanforyou23

**Comment by riccardo-forina** [comment]
There is no pagination implemented anywhere in the whole app afaik.

**Comment by dongniwang** [comment]
@riccardo-forina 

> There is no pagination implemented anywhere in the whole app afaik.

Good to know. I don't think we necessarily need that for this screen. But could be a desirable feature in the future for other use cases - especially for a table with hundreds of rows.

**Pull request merged**
