### PR TITLE
Home/Dashboard

### PR DESCRIPTION
**Pull request by kahboom**
- Limit Connections to 8
- Format numbers & dates
- Aesthetic improvements

Screenshot 2019-05-09 19 29 43

Screenshot 2019-05-09 19 29 54

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1270/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
Looking at the screen, isn’t the integration area missing the right alignments? It stretches too much and there is no spacing between the columns. On mobile it doesn’t switch to a column based view, that should be checked too.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1272/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1279/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by kahboom** [comment]
screencapture-localhost-3000-2019-05-10-14_14_54

screencapture-localhost-3000-2019-05-10-14_15_57

**Comment by kahboom** [comment]
screencapture-localhost-3000-2019-05-10-17_39_54

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1283/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1304/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1306/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by kahboom** [comment]
Think I finally fixed it.. it's not 100% pixel perfect but I think close enough.

Desktop:

Screenshot 2019-05-13 11 11 57



Mobile:

screencapture-localhost-3000-2019-05-13-11_11_17

**Pull request merged**
