### PR TITLE
chore: add an array story to auto-form, add some tweaks and guards too

### LINKED ISSUE #334: connection detail - validation logic isn't correct
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
While refactoring the forms I've found that the logic for the `validate` button isn't correct on the connection detail page and the connector form page in the connection creation wizard.  The `validate` button only sends the current form values to the backend to show the user if the current settings are correct or not.  Validation of required fields etc. are all left to the form property definition, and the response back from the backend is either no errors, meaning that whatever the user has entered was successful in creating a connection, or an error response that carries the error reported by the camel connector making a connection attempt to the target system.

I'm hoping to fix this as part of my form refactoring effort but I may need to track this as a separate effort.

### LINKED ISSUE #345: auto-form - enhance property definition validation to work with array properties
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Currently the `validateRequiredProperties` function can only operate on a flat map of properties, however we now can support properties of an `array` type that contain a property definition for each element of the array.  The `validateRequiredProperties` function needs to be enhanced for the `array` property by validating each element of the property value against the `arrayDefinitionProperty` field that would be set on that particular property.  If an array element is invalid, then the validator needs to construct a property name string that Formik will understand based on the property name, index in the array and the field name in the property array.  So for example given a definition like:

```
{
  foo: {
    arrayDefinition: {
       bar: {
          type: 'text'
       }
    },
    type: 'array'
  }
}
```

And then some input data like: 

```
{
   foo: [ { bar: 'blah' }, { bar: '' }]
}
```

The resulting validation error object should look like:

```
{
   "foo[1].bar": "Property \"bar\" is required"
}
```

With that notation Formik will know which element in the form the validation result applies to and can set the appropriate state for that control.

### LINKED ISSUE #352: auto-form - add control buttons to array control area to move rows up and down
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
As part of supporting the conditional flow UI we'll need a means of ordering the rows that the array form component creates.

We could add buttons, we may also want to consider some kind of drag/drop support with the buttons as a fallback perhaps.

### PR DESCRIPTION
**Pull request by gashcrumb**
prep work for #255 
fixes #352
fixes #345 
fixes #334

image

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1838/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1841/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1843/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1845/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1847/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1880/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1895/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
Yeah, this is ready to go in.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1898/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Pull request merged**
