### PR TITLE
feat: Implement conditional flows

### LINKED ISSUE #255: Editor - Implement the conditional flow step
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
We'll need to port [this PR](https://github.com/syndesisio/syndesis/pull/5322)

### PR DESCRIPTION
**Pull request by gashcrumb**
fixes #255

image

image

image

image

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/2112/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
Ready to go, added labels to the dropdown it felt like they were needed, conditional flow dropdown is set up the same as the angular app.

**Comment by gashcrumb** [comment]
@riccardo-forina yeah, this PR doesn't address the page at all, only the breadcrumbs.  That's next.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/2150/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
I think I found a problem: Integrations > Test - edit -> Create flow (anyone) -> boom

```
react-dom.production.min.js:4408 TypeError: Cannot read property 'id' of undefined
    at Ui (EditorBreadcrumb.tsx:84)
    at Zo (react-dom.production.min.js:3274)
    at La (react-dom.production.min.js:3899)
    at qi (react-dom.production.min.js:5514)
    at Yi (react-dom.production.min.js:5536)
    at Mc (react-dom.production.min.js:5958)
    at zc (react-dom.production.min.js:5925)
    at Ac (react-dom.production.min.js:6020)
    at En (react-dom.production.min.js:1737)
```

**Comment by gashcrumb** [comment]
Squashed that, thanks for catchin' it!

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/2159/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
Added the "back" button to the menu.  I'll probably just push more stuff onto this branch so marking wip again :-)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/2167/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
I did hit this when saving a new flow, but I don't think I touched this area in this PR:

image

Seems like the `new-integration` ID there isn't getting removed, maybe this branch just needs a rebase?  Dunno, going to 🛌

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/2172/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
No that’s on me not getting how `immer` works. I’ll fix it in another pr

**Pull request merged**
