### PR TITLE
feat: Implement the 'describe data' page

### LINKED ISSUE #253: Editor - implement "describe data" page
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Any connection that has a datashape of type `ANY` can accept user-provided data shape information.  This is done after [action configuration](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts#L165-L180) via the "describe data" page:

image

The entire form here is implemented using the angular app's equivalent to auto-form, the [configuration](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts#L40-L88) can probably be used as-is with auto-form.

Depending on where the step is in the integration flow the user could be prompted to supply one or more data shapes:

1. Start position -> output data shape
2. Middle position -> input and output data shapes
3. End position -> input data shape

Upon clicking next the page [maps the form data](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts#L173-L201) to a `descriptor` object containing the data shapes.

In the angular codebase the user is unconditionally sent to the describe data page, and the page determines if the user should be prompted, if not then the user is just redirected back to the save/add step page.

### PR DESCRIPTION
**Pull request by gashcrumb**
fixes #253  Also fixes the editor in the template step, it sucked.

image

todo -> saving...

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1427/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
Nice, it looks like in my latest refactoring I tried to be smart with Typescript but I have actually been dumb. I managed to disable the typecheck for the routers 😅
Fixing it, will push an update soon (🤞).

**Comment by riccardo-forina** [comment]
Ok this should unstuck you.

About this point: https://github.com/syndesisio/syndesis-react/pull/292/files#diff-36b7e5dcd942fffae574743a50ebca70R115

I think this will eventually look something like this:

```tsx
postConfigureHref={(requiresDataShape, integration, p, s) =>
  requiresDataShape
    ? (
      appResolvers.connection.describeData({
        ...p,
        ...s,
      })
    ) : (
      postConfigureHref
    )
}
```

to support connectors that require an additional configuration and those that don't, right?

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1432/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
> to support connectors that require an additional configuration and those that don't, right?

It will now, hadn't thought that far ahead yet, thanks!

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1489/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1495/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
Maybe we could merge this and I'll follow up with a second PR to finish up the saving and routing logic.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1500/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Pull request merged**
