### PR TITLE
defer registering the service worker until the app loads it's config

### PR DESCRIPTION
**Pull request by gashcrumb**

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/2430/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
Now that I think about that, the `config.json` isn't under auth on CI, so we can't really check this out without merging (or testing on minishift I guess?)

**Comment by gashcrumb** [comment]
Yeah, I think so, no biggie I will give it a test later on today.  My Chrome instance is in just the right state with a stale auth token also and this obviously hasn't changed things :smile:

**Comment by gashcrumb** [comment]
What I might do then is wait until the call to `https://syndesis-staging-2.b6ff.rh-idev.openshiftapps.com/api/v1/users/~` succeeds since we always make that anyways and see if that does the trick.

**Comment by gashcrumb** [comment]
Made that change, will see if that helps things.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/2445/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Pull request merged**
