### PR TITLE
API Editor UI Round II

### PR DESCRIPTION
**Pull request by kahboom**
Trello card: https://trello.com/c/q73yIflP/8-m-api-provider-editor

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1916/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1922/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1935/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1952/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1957/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1969/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by kahboom** [comment]
Select Method:

Screenshot 2019-05-30 10 13 29

Screenshot 2019-05-30 10 13 41


Review Actions Page:

Screenshot 2019-05-30 10 13 53


Operations Page:

screencapture-localhost-3000-integrations-create-Lg30OWn-loFFcsTonkJ-configure-editor-operations-2019-05-30-10_09_56

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1972/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by kahboom** [comment]
I may be biased, but I think this looks pretty good (enough).. 🤷🏻‍♀️

**Pull request merged**
