### PR TITLE
feat: add ci/cd elements and storybook, wire up operations

### LINKED ISSUE #158: Create CI/CD elements and storybook.
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Need to create page elements for the CI/CD page and dialog and a corresponding storybook.

Design at -> https://redhat.invisionapp.com/share/36QTHNFFCUB

Previous design for reference (what the angular app implements) -> https://redhat.invisionapp.com/share/E9QCV528WVN#/screens/345130936

### LINKED ISSUE #164: Wire CI/CD page into app
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
With all the UI elements in place (#161) next step is to wire them into the app.

### LINKED ISSUE #165: Create tag integration with environment dialog
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The 'ci/cd' menu item should bring up a dialog that lists the available environments and allow the user to check which environments the integration should be tagged with.

https://redhat.invisionapp.com/share/36QTHNFFCUB#/screens/350160532

### LINKED ISSUE #166: MessageDialog adds an extra div under it's modal-body div
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
While implementing dialogs I'm finding their layout isn't right.  As it turns out, the MessageDialog from patternfly-react seems to add an extra div that shows up like `<div id>` under the `modal-body`.  Perhaps I'm missing a setting, but the result is:

image

See how the list item lines don't occupy the whole modal body?

### PR DESCRIPTION
**Pull request by gashcrumb**
fixes #158
fixes #164 
fixes #165
fixes #166 kinda sorta

This implements the CI/CD design end to end, though to work fully 3 changes to the backend are needed,  [#5266](https://github.com/syndesisio/syndesis/issues/5266) and [#5263](https://github.com/syndesisio/syndesis/issues/5263) and [#5267](https://github.com/syndesisio/syndesis/issues/5267)

### CODE REVIEW

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/685/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
Looking good! For some reason, the action buttons are clickable only near the borders on my Chrome (incognito or not), but they work fine on FF. Do you see the same?

**Comment by gashcrumb** [comment]
I do!  I'm probably not using the patternfly-react buttons properly, but I
haven't worried about it yet, mostly wanted to get to this off the laptop
just to be on the safe side :-). That being said there's no docs in the
button's storybook and it's just a re-export looks like, sheesh...

**Comment by riccardo-forina** [comment]
Try using the `<ButtonLink>` component, also from the ui package, the interface should be the same.

**Comment by gashcrumb** [comment]
Yup, will give that a go.  That's an odd behavior for their button component though :-)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/696/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/701/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/705/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/707/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
Interesting, so the button issue shown in the storybook is because the `list-group-item-text` div that holds the `used by n integrations` is for whatever reason spilled out and over the button area and partially covering them:

image

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/710/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
Found a workaround I guess, the list needs the `additionalInfo` column set to calculate widths, so added in an empty span.  Other than that I think there's not much else I can do for the UI on this one,

**Comment by gashcrumb** [comment]
@dongniwang FYI if you want, check out the storybook link under 'CiCd'.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/712/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
This does have a few issues here and there that I'm addressing in a subsequent PR as I start to use these UI elements.

**Comment by gashcrumb** [comment]
Well, this work has to park for now.  The environment tag API isn't quite correct to implement the new design for the CI/CD management page, but in any case this PR is ready to be merged, it fetches environments, you just can't create/edit/remove them:

image

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/714/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
The `Add New` button won't work until there's an API to support it.  For now it looks like it does something but it's a lie :fearful:

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/716/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/718/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/720/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/722/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/724/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/726/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/728/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/730/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by dongniwang** [comment]
Thank you @gashcrumb! - But I saw a blank CI/CD management page using link from this commenet https://github.com/syndesisio/syndesis-react/pull/161#issuecomment-485428336... should I check back later?

**Comment by dongniwang** [comment]
@gashcrumb - nvm, was looking at the wrong page...found it now

**Comment by gashcrumb** [comment]
It's implemented, barring two needed changes to the API, #5266 and #5263.

Need to add some strings to the locale file, and the dialog for marking an integration for CI/CD was a bit tricky to implement, so may revisit that further.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/739/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/746/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
Cleaned up PR storybook links, accumulated quite a few!  :smile_cat:

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/751/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
> Whoa! Who said the CI thing was a small one?

Right?

**Pull request merged**
