### PR TITLE
chore(pf4-styles): integration list styles, about modal, pf deps

### PR DESCRIPTION
**Pull request by seanforyou23**
This PR updates patternfly dependency versions, fixes some minor layout issues in the integration list view, and applies the pf4 downstream background to the about modal. Oh and also updates the favicon(s) to the new Red Hat favicon.

Screen Shot 2019-05-17 at 10 14 35 AM

Screen Shot 2019-05-17 at 4 15 31 PM

Screen Shot 2019-05-17 at 4 16 04 PM

Should we take this time to make these product related images configurable? We could give similar treatment for the logo and update the favicon all together. What do you think @gashcrumb @dongniwang

### CODE REVIEW

**Comment by gashcrumb** [comment]
> Should we take this time to make these product related images configurable?
+1 wanna raise an issue for that or do it in this PR?

**Comment by dongniwang** [comment]
> Should we take this time to make these product related images configurable?

+1 to this as well!

**Comment by seanforyou23** [comment]
I'll work on it here in this PR

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/1556/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Pull request merged**
